#!/bin/bash
#password prompt to access terminal (just for looks, not really secure)
#code should be placed in .bashrc
#current password = pencil (change accordingly)
#your password will remain invisible but its ok, right?
#comment out username/greeting if not needed 

clear
sleep 0.5
echo
echo
read -p "Username: " user #can be anything, no right or wrong answer here.
echo
echo "Greetings, $user. "
echo

read -s -p "Password: " pass 
echo
 if [ $pass = pencil ]
    then printf "\nWelcome. "
echo
    else printf "\nWrong. Try again? \n"
echo
read -s -p "Password: " pass
echo
   if [ $pass = pencil ]
    then printf "\nGood answer. "
echo
    else printf "\nWrong again. But thats ok.. "
   fi
 fi
sleep 0.5
echo
echo
